// Build-time codegen: reads modules/*/module.yaml + preset.yaml,
// generates src/hooks/generated/module-registry.ts with typed constants.

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { parse } from 'yaml';

const ROOT = resolve(import.meta.dirname, '..');
const MODULES_DIR = join(ROOT, 'modules');
const OUTPUT_FILE = join(ROOT, 'src', 'hooks', 'generated', 'module-registry.ts');

interface RawModuleCapability {
  tool: string;
  default_level?: number;
  preset?: string;
  rulesets?: string[];
  presets?: string[];
}

interface RawModule {
  name: string;
  label: string;
  language: string;
  framework: string;
  capabilities: Record<string, RawModuleCapability>;
}

interface RawPresetTool {
  binary: string;
  config?: string;
  level?: number;
  preset?: string;
  rulesets?: string[];
  extensions?: string[];
  directory?: string;
}

interface RawPreset {
  tools: Record<string, RawPresetTool>;
  install_commands: string[];
}

interface ModuleRegistryEntry {
  module: RawModule;
  preset: RawPreset;
}

const registry: Record<string, ModuleRegistryEntry> = {};

for (const dir of readdirSync(MODULES_DIR)) {
  const moduleYamlPath = join(MODULES_DIR, dir, 'module.yaml');
  const presetYamlPath = join(MODULES_DIR, dir, 'preset.yaml');

  if (!existsSync(moduleYamlPath)) continue;

  const moduleData = parse(readFileSync(moduleYamlPath, 'utf-8')) as RawModule;

  let presetData: RawPreset = { tools: {}, install_commands: [] };
  if (existsSync(presetYamlPath)) {
    presetData = parse(readFileSync(presetYamlPath, 'utf-8')) as RawPreset;
  }

  registry[moduleData.name] = { module: moduleData, preset: presetData };
}

const output = `// AUTO-GENERATED by scripts/generate-module-registry.ts — DO NOT EDIT
import type { ModuleDefinition, PresetDefinition } from '../../core/types/index.js';

interface ModuleRegistryEntry {
  module: ModuleDefinition;
  preset: PresetDefinition;
}

export const MODULE_REGISTRY: Record<string, ModuleRegistryEntry> = ${JSON.stringify(registry, null, 2)} as const;
`;

writeFileSync(OUTPUT_FILE, output, 'utf-8');

const moduleNames = Object.keys(registry);
console.log(`Generated module registry with ${moduleNames.length} module(s): ${moduleNames.join(', ')}`);
