// Main entry point — re-exports core types for public API
export type {
  Severity,
  AnalysisViolation,
  ToolError,
  ToolResult,
  AnalysisResult,
  Enforcement,
  ToolConfig,
  CapabilityConfig,
  PatternsConfig,
  ThresholdsConfig,
  HookConfig,
  BaselineConfig,
  ProjectConfig,
  CodeGuardConfig,
  CommandSpec,
  DetectionSignal,
  PatternDetection,
  PatternVerification,
  PatternExamples,
  PatternDefinition,
  ModuleCapability,
  ModuleDetection,
  ModuleDefinition,
  PresetTool,
  PresetDefinition,
  DetectionResult,
  ToolAdapter,
  FormatterContext,
  OutputFormatter,
} from './core/types/index.js';
